name: CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build with Gradle Wrapper
        run: ./gradlew bootBuildImage --imageName "ghcr.io/${REPO,,}":${{ github.sha }}
        env:
          REPO: '${{ github.repository }}'
