spring:
  kafka:

    producer:
      bootstrap-servers: "localhost:9094"

    consumer:
      group-id: mm
      bootstrap-servers: "localhost:9092"
      properties:
        auto.offset.reset: earliest

application:
  backupTopics: [ ]
  restoreTopics: { }

mirror:
  topics:
  allowedTopicPattern: "".*"
  allowedConfigrationPattern: ".*"
  deniedConfigrationPattern: ""
